# Generated by Django 5.2.7 on 2025-10-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('home_team', models.CharField(max_length=255)),
                ('away_team', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='events/posters/')),
                ('venue', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
    ]
