# Generated by Django 5.2.7 on 2025-10-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('badminton', 'Badminton'), ('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball')], default='football', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='match_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
