# Generated by Django 5.2.7 on 2025-10-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='match_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
