# Generated by Django 5.2.7 on 2025-10-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('badminton', 'Badminton'), ('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis'), ('volleyball', 'Volleyball')], default='football', max_length=20),
        ),
    ]
