# Generated by Django 5.2.7 on 2025-10-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
