# Generated by Django 5.2.7 on 2025-10-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='id',
        ),
        migrations.AlterField(
            model_name='event',
            name='match_id',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
