# Generated by Django 5.2.7 on 2025-10-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_event_id_alter_event_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='match_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
