# Generated by Django 5.2.7 on 2025-10-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_poster'),
        ('event', '0005_event_id_alter_event_match_id'),
    ]

    operations = [
    ]
