# Generated by Django 5.2.7 on 2025-10-25 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('ticket', '0002_alter_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ticket.ticket'),
        ),
    ]
