# Generated by Django 5.2.7 on 2025-10-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
