# Generated by Django 5.2.7 on 2025-10-24 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_harga_order_kategori_order_match_id_and_more'),
        ('ticket', '0002_alter_ticket_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='order',
            name='match_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='ticket',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ticket.ticket'),
        ),
    ]
